# Generated by Django 4.2.19 on 2025-03-24 12:11

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('dynasty', models.CharField(max_length=50, verbose_name='朝代')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=book.models.book_cover_upload_to, verbose_name='封面')),
                ('content_file', models.FileField(blank=True, null=True, upload_to=book.models.book_content_upload_to, verbose_name='内容文件')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'db_table': 'sys_book',
            },
        ),
    ]
