# Generated by Django 4.2.19 on 2025-03-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content_encoding',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='内容文件编码'),
        ),
    ]
