# Generated by Django 5.0.1 on 2024-07-29 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_sysuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='菜单名称')),
                ('icon', models.CharField(max_length=100, null=True, verbose_name='菜单图标')),
                ('parent_id', models.IntegerField(max_length=11, null=True, verbose_name='父菜单ID')),
                ('order_num', models.IntegerField(max_length=11, null=True, verbose_name='显示顺序')),
                ('path', models.CharField(max_length=200, null=True, verbose_name='路由地址')),
                ('component', models.CharField(max_length=255, null=True, verbose_name='组件路径')),
                ('menu_type', models.CharField(max_length=1, null=True, verbose_name='菜单类型（M目录 C菜单 F按钮）')),
                ('perms', models.CharField(max_length=100, null=True, verbose_name='权限标识')),
                ('create_time', models.DateField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(null=True, verbose_name='更新时间')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True, verbose_name='角色名称')),
                ('code', models.CharField(max_length=100, null=True, verbose_name='角色权限字符串')),
                ('create_time', models.DateField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(null=True, verbose_name='更新时间')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='SysRoleMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.sysmenu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.sysrole')),
            ],
        ),
        migrations.CreateModel(
            name='SysUserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.sysrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.sysuser')),
            ],
        ),
    ]
