# Generated by Django 5.0.1 on 2024-07-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_sysmenu_sysrole_sysrolemenu_sysuserrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmenu',
            name='order_num',
            field=models.IntegerField(null=True, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='parent_id',
            field=models.IntegerField(null=True, verbose_name='父菜单ID'),
        ),
    ]
