# Generated by Django 5.0.1 on 2024-08-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_sysmenu_table_alter_sysrole_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='status',
            field=models.IntegerField(null=True, verbose_name='帐号状态（0正常 1停用）'),
        ),
    ]
